In [1]:
import os
import random

# suppress the TensorFlow warning
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import numpy as  np
from keras.models import load_model

/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
def encode(X,seq_len, vocab_size):
    x = np.zeros((len(X),seq_len, vocab_size), dtype=np.float32)
    for ind,batch in enumerate(X):
        for j, elem in enumerate(batch):
            x[ind, j, elem] = 1
    return x

In [3]:
model = load_model('model.h5')

In [4]:
seq_len = 15 # number of elements in sequence to sort
max_no = 100 # upper range of the numbers in sequence
win_cnt = 0
numb_trials = 1000

In [5]:
for ii in range(numb_trials):
    testX = np.random.randint(max_no, size=(1, seq_len))
    test = encode(testX, seq_len, max_no)
    y = model.predict(test, batch_size=1)
    print(testX, ': input array')
    np_sorted = np.sort(testX)[0]
    rnn_sorted = np.argmax(y, axis=2)[0]
    is_equal = np.array_equal(np_sorted, rnn_sorted)
    if is_equal: win_cnt += 1
    print(np_sorted, ': sorted by NumPy algorithm')
    print(rnn_sorted, ': sorted by trained RNN')
    print("\n")

(array([[35, 65, 65, 19, 48, 76, 50, 94, 21, 30, 42, 60, 55, 73, 61]]), ': input array')
(array([19, 21, 30, 35, 42, 48, 50, 55, 60, 61, 65, 65, 73, 76, 94]), ': sorted by NumPy algorithm')
(array([19, 21, 30, 35, 42, 48, 50, 55, 60, 61, 65, 65, 73, 76, 94]), ': sorted by trained RNN')


(array([[ 0, 78, 43, 62, 51, 86, 28,  5, 74, 59,  6, 75, 59, 40, 30]]), ': input array')
(array([ 0,  5,  6, 28, 30, 40, 43, 51, 59, 59, 62, 74, 75, 78, 86]), ': sorted by NumPy algorithm')
(array([ 0,  5,  6, 28, 30, 40, 43, 51, 59, 59, 62, 74, 75, 78, 86]), ': sorted by trained RNN')


(array([[43, 73, 15, 38, 42, 80, 69, 64, 33,  0, 58, 37,  9, 11, 75]]), ': input array')
(array([ 0,  9, 11, 15, 33, 37, 38, 42, 43, 58, 64, 69, 73, 75, 80]), ': sorted by NumPy algorithm')
(array([ 0,  9, 11, 15, 33, 37, 38, 42, 43, 58, 64, 69, 73, 75, 80]), ': sorted by trained RNN')


(array([[78, 59, 16, 46, 88,  7, 69, 39,  7, 86, 48, 50,  8, 76, 55]]), ': input array')
(array([ 7,  7,  8, 16, 39, 46, 48, 50, 55, 

(array([[41, 91, 43, 70, 99, 23,  2, 54, 60, 71, 47, 90,  0,  9,  6]]), ': input array')
(array([ 0,  2,  6,  9, 23, 41, 43, 47, 54, 60, 70, 71, 90, 91, 99]), ': sorted by NumPy algorithm')
(array([ 0,  2,  6,  9, 23, 41, 43, 47, 54, 60, 70, 71, 90, 91, 99]), ': sorted by trained RNN')


(array([[30, 45, 68, 48, 65, 21, 57, 35, 66,  6, 35, 77, 41, 43, 72]]), ': input array')
(array([ 6, 21, 30, 35, 35, 41, 43, 45, 48, 57, 65, 66, 68, 72, 77]), ': sorted by NumPy algorithm')
(array([ 6, 21, 30, 35, 35, 41, 43, 45, 48, 57, 65, 66, 68, 72, 77]), ': sorted by trained RNN')


(array([[ 1, 54, 85, 10, 58, 54, 61, 25,  0, 60, 50, 85, 38, 21,  7]]), ': input array')
(array([ 0,  1,  7, 10, 21, 25, 38, 50, 54, 54, 58, 60, 61, 85, 85]), ': sorted by NumPy algorithm')
(array([ 0,  1,  7, 10, 21, 25, 38, 50, 54, 54, 58, 60, 61, 85, 85]), ': sorted by trained RNN')


(array([[ 0, 31, 84, 39, 96, 24, 96, 84, 73, 36, 45, 90, 26, 80,  5]]), ': input array')
(array([ 0,  5, 24, 26, 31, 36, 39, 45, 73, 

(array([[36, 37, 53,  2, 65, 96, 13, 19, 56, 89,  5, 71, 16, 11, 30]]), ': input array')
(array([ 2,  5, 11, 13, 16, 19, 30, 36, 37, 53, 56, 65, 71, 89, 96]), ': sorted by NumPy algorithm')
(array([ 2,  5, 11, 13, 16, 19, 30, 36, 37, 53, 56, 65, 71, 89, 96]), ': sorted by trained RNN')


(array([[87, 55, 22, 40, 51, 40, 58,  5, 83, 89, 21, 60, 23, 68, 27]]), ': input array')
(array([ 5, 21, 22, 23, 27, 40, 40, 51, 55, 58, 60, 68, 83, 87, 89]), ': sorted by NumPy algorithm')
(array([ 5, 21, 22, 23, 27, 40, 40, 51, 55, 58, 60, 68, 83, 87, 89]), ': sorted by trained RNN')


(array([[78, 67, 97, 73, 83, 92, 48, 40, 94, 76, 21,  8, 40, 58, 66]]), ': input array')
(array([ 8, 21, 40, 40, 48, 58, 66, 67, 73, 76, 78, 83, 92, 94, 97]), ': sorted by NumPy algorithm')
(array([ 8, 21, 40, 40, 48, 58, 66, 67, 73, 76, 78, 83, 92, 94, 97]), ': sorted by trained RNN')


(array([[13, 36,  8, 98, 21, 89, 37, 15, 25, 66, 57, 91, 82, 98, 46]]), ': input array')
(array([ 8, 13, 15, 21, 25, 36, 37, 46, 57, 

(array([[80, 60, 79,  6, 63, 27,  5,  4,  5, 20, 95,  1, 87, 11, 25]]), ': input array')
(array([ 1,  4,  5,  5,  6, 11, 20, 25, 27, 60, 63, 79, 80, 87, 95]), ': sorted by NumPy algorithm')
(array([ 1,  4,  5,  5,  6, 11, 20, 25, 27, 60, 63, 79, 80, 87, 95]), ': sorted by trained RNN')


(array([[27, 55, 19, 86, 10, 99,  1, 91, 68, 29, 77, 96, 85, 20, 22]]), ': input array')
(array([ 1, 10, 19, 20, 22, 27, 29, 55, 68, 77, 85, 86, 91, 96, 99]), ': sorted by NumPy algorithm')
(array([ 1, 10, 19, 20, 22, 27, 29, 55, 68, 77, 85, 86, 91, 96, 99]), ': sorted by trained RNN')


(array([[16, 40,  3,  7, 72, 96, 34, 47, 45, 28, 94, 65,  9, 12, 90]]), ': input array')
(array([ 3,  7,  9, 12, 16, 28, 34, 40, 45, 47, 65, 72, 90, 94, 96]), ': sorted by NumPy algorithm')
(array([ 3,  7,  9, 12, 16, 28, 34, 40, 45, 47, 65, 72, 90, 94, 96]), ': sorted by trained RNN')


(array([[35, 68, 79, 30, 73, 42, 70, 81,  8, 61, 65, 82,  9,  6, 10]]), ': input array')
(array([ 6,  8,  9, 10, 30, 35, 42, 61, 65, 

(array([[72,  7, 56, 70,  4, 93, 22, 95, 47, 52, 47, 66, 59, 87, 97]]), ': input array')
(array([ 4,  7, 22, 47, 47, 52, 56, 59, 66, 70, 72, 87, 93, 95, 97]), ': sorted by NumPy algorithm')
(array([ 4,  7, 22, 47, 47, 52, 56, 59, 66, 70, 72, 87, 93, 95, 97]), ': sorted by trained RNN')


(array([[30, 99, 59, 72, 31, 56, 20,  8, 86, 18, 24, 87,  0, 15, 89]]), ': input array')
(array([ 0,  8, 15, 18, 20, 24, 30, 31, 56, 59, 72, 86, 87, 89, 99]), ': sorted by NumPy algorithm')
(array([ 0,  8, 15, 18, 20, 24, 30, 31, 56, 59, 72, 86, 87, 89, 99]), ': sorted by trained RNN')


(array([[43,  2,  6,  5, 81, 62,  7, 72, 37, 59, 75, 20, 53, 34, 12]]), ': input array')
(array([ 2,  5,  6,  7, 12, 20, 34, 37, 43, 53, 59, 62, 72, 75, 81]), ': sorted by NumPy algorithm')
(array([ 2,  5,  6,  7, 12, 20, 34, 37, 43, 53, 59, 62, 72, 75, 81]), ': sorted by trained RNN')


(array([[81,  4, 63, 97, 24, 97, 34, 60, 87, 38, 85, 60, 90, 29, 42]]), ': input array')
(array([ 4, 24, 29, 34, 38, 42, 60, 60, 63, 

(array([[65, 20, 73, 67, 37, 73,  6,  0,  9, 10, 25, 39, 53, 11, 50]]), ': input array')
(array([ 0,  6,  9, 10, 11, 20, 25, 37, 39, 50, 53, 65, 67, 73, 73]), ': sorted by NumPy algorithm')
(array([ 0,  6,  9, 10, 11, 20, 25, 37, 39, 50, 53, 65, 67, 73, 73]), ': sorted by trained RNN')


(array([[64, 73,  1, 35, 51, 77, 46, 87, 49, 32, 83, 69, 91,  3, 98]]), ': input array')
(array([ 1,  3, 32, 35, 46, 49, 51, 64, 69, 73, 77, 83, 87, 91, 98]), ': sorted by NumPy algorithm')
(array([ 1,  3, 32, 35, 46, 49, 51, 64, 69, 73, 77, 83, 87, 91, 98]), ': sorted by trained RNN')


(array([[96, 59, 80, 20,  3, 26, 29, 60, 82, 54,  2, 52, 76, 87, 62]]), ': input array')
(array([ 2,  3, 20, 26, 29, 52, 54, 59, 60, 62, 76, 80, 82, 87, 96]), ': sorted by NumPy algorithm')
(array([ 2,  3, 20, 26, 29, 52, 54, 59, 60, 62, 76, 80, 82, 87, 96]), ': sorted by trained RNN')


(array([[79, 72, 43, 20, 81, 88, 58,  0, 26, 98, 60,  5, 69, 79, 35]]), ': input array')
(array([ 0,  5, 20, 26, 35, 43, 58, 60, 69, 

(array([[79, 70, 59, 52, 98, 46, 76, 69, 34, 73, 78, 10,  9, 40, 17]]), ': input array')
(array([ 9, 10, 17, 34, 40, 46, 52, 59, 69, 70, 73, 76, 78, 79, 98]), ': sorted by NumPy algorithm')
(array([ 9, 10, 17, 34, 40, 46, 52, 59, 69, 70, 73, 76, 78, 79, 98]), ': sorted by trained RNN')


(array([[ 1, 68, 52, 68, 51, 42, 44, 96, 27, 64, 44, 91,  0, 54, 20]]), ': input array')
(array([ 0,  1, 20, 27, 42, 44, 44, 51, 52, 54, 64, 68, 68, 91, 96]), ': sorted by NumPy algorithm')
(array([ 0,  1, 20, 27, 43, 44, 44, 51, 52, 54, 64, 68, 68, 91, 96]), ': sorted by trained RNN')


(array([[73, 60, 66, 75, 40, 75, 36, 65, 49, 40, 58, 61, 13, 69, 17]]), ': input array')
(array([13, 17, 36, 40, 40, 49, 58, 60, 61, 65, 66, 69, 73, 75, 75]), ': sorted by NumPy algorithm')
(array([13, 17, 35, 40, 40, 49, 58, 60, 61, 65, 66, 69, 73, 75, 75]), ': sorted by trained RNN')


(array([[80, 59, 90,  0, 49, 36, 20, 97, 19, 54, 64, 38, 54, 99, 79]]), ': input array')
(array([ 0, 19, 20, 36, 38, 49, 54, 54, 59, 

(array([[ 3, 38, 99, 10,  2, 13, 34, 99, 47, 27, 45, 13, 60, 10, 55]]), ': input array')
(array([ 2,  3, 10, 10, 13, 13, 27, 34, 38, 45, 47, 55, 60, 99, 99]), ': sorted by NumPy algorithm')
(array([ 2,  3, 10, 10, 13, 13, 27, 34, 38, 45, 47, 55, 60, 99, 99]), ': sorted by trained RNN')


(array([[71,  4, 26, 50, 18, 64, 43, 16, 83, 43, 85, 54, 31, 84, 52]]), ': input array')
(array([ 4, 16, 18, 26, 31, 43, 43, 50, 52, 54, 64, 71, 83, 84, 85]), ': sorted by NumPy algorithm')
(array([ 4, 16, 18, 26, 31, 43, 43, 50, 52, 54, 64, 71, 83, 84, 85]), ': sorted by trained RNN')


(array([[30, 84, 83, 43, 45, 79,  2, 50, 26, 79, 79, 57, 48, 26, 94]]), ': input array')
(array([ 2, 26, 26, 30, 43, 45, 48, 50, 57, 79, 79, 79, 83, 84, 94]), ': sorted by NumPy algorithm')
(array([ 2, 26, 26, 30, 43, 45, 48, 50, 57, 79, 79, 79, 83, 84, 94]), ': sorted by trained RNN')


(array([[22, 59, 49, 79, 26, 94, 36, 31, 93, 80, 17, 45, 27, 88, 90]]), ': input array')
(array([17, 22, 26, 27, 31, 36, 45, 49, 59, 

(array([[45, 85, 92, 96, 36, 34, 23, 32, 66, 17,  8, 68, 55,  0, 73]]), ': input array')
(array([ 0,  8, 17, 23, 32, 34, 36, 45, 55, 66, 68, 73, 85, 92, 96]), ': sorted by NumPy algorithm')
(array([ 0,  8, 17, 23, 32, 34, 36, 45, 55, 66, 68, 73, 85, 92, 96]), ': sorted by trained RNN')


(array([[73, 52, 73, 61, 97, 35, 72, 95,  5, 42, 99, 19, 54, 44, 92]]), ': input array')
(array([ 5, 19, 35, 42, 44, 52, 54, 61, 72, 73, 73, 92, 95, 97, 99]), ': sorted by NumPy algorithm')
(array([ 5, 19, 35, 42, 44, 52, 54, 61, 72, 73, 73, 92, 95, 97, 99]), ': sorted by trained RNN')


(array([[80, 72, 95, 92,  4, 16, 76, 16,  2, 87, 47, 82, 35, 57, 57]]), ': input array')
(array([ 2,  4, 16, 16, 35, 47, 57, 57, 72, 76, 80, 82, 87, 92, 95]), ': sorted by NumPy algorithm')
(array([ 2,  4, 16, 16, 35, 47, 57, 57, 72, 76, 80, 82, 87, 92, 95]), ': sorted by trained RNN')


(array([[46, 32, 94, 48, 66, 92, 58, 81, 81, 73, 86, 64, 78, 87, 65]]), ': input array')
(array([32, 46, 48, 58, 64, 65, 66, 73, 78, 

(array([[47, 23, 92, 70,  2, 66, 14, 29, 68, 60, 22, 45, 42, 50, 93]]), ': input array')
(array([ 2, 14, 22, 23, 29, 42, 45, 47, 50, 60, 66, 68, 70, 92, 93]), ': sorted by NumPy algorithm')
(array([ 2, 14, 22, 23, 29, 42, 45, 47, 50, 60, 66, 68, 70, 92, 93]), ': sorted by trained RNN')


(array([[13,  8, 90, 57, 57, 89, 26, 55, 58, 14, 90,  1, 97, 59,  0]]), ': input array')
(array([ 0,  1,  8, 13, 14, 26, 55, 57, 57, 58, 59, 89, 90, 90, 97]), ': sorted by NumPy algorithm')
(array([ 0,  1,  8, 13, 14, 26, 55, 57, 57, 58, 59, 89, 90, 90, 97]), ': sorted by trained RNN')


(array([[28, 13, 37, 35, 96, 78, 52, 32, 35, 93, 34, 33, 60, 96, 95]]), ': input array')
(array([13, 28, 32, 33, 34, 35, 35, 37, 52, 60, 78, 93, 95, 96, 96]), ': sorted by NumPy algorithm')
(array([13, 28, 32, 33, 34, 35, 35, 37, 52, 60, 78, 93, 95, 96, 96]), ': sorted by trained RNN')


(array([[44, 90, 39, 84, 71,  2, 31, 11, 97, 67, 29, 98,  6,  8, 68]]), ': input array')
(array([ 2,  6,  8, 11, 29, 31, 39, 44, 67, 

(array([[55, 22, 86, 18, 44, 40, 50, 47, 16, 26,  1, 11, 89, 27, 61]]), ': input array')
(array([ 1, 11, 16, 18, 22, 26, 27, 40, 44, 47, 50, 55, 61, 86, 89]), ': sorted by NumPy algorithm')
(array([ 1, 11, 16, 18, 22, 26, 27, 40, 44, 47, 50, 55, 61, 86, 89]), ': sorted by trained RNN')


(array([[82, 95, 63, 22, 38, 84, 41, 54, 69, 64, 90, 77, 19, 20, 76]]), ': input array')
(array([19, 20, 22, 38, 41, 54, 63, 64, 69, 76, 77, 82, 84, 90, 95]), ': sorted by NumPy algorithm')
(array([19, 20, 22, 38, 41, 54, 63, 64, 69, 76, 77, 82, 84, 90, 95]), ': sorted by trained RNN')


(array([[94, 48, 20, 74, 60, 30, 97, 75, 22, 32, 18, 40, 34,  9, 51]]), ': input array')
(array([ 9, 18, 20, 22, 30, 32, 34, 40, 48, 51, 60, 74, 75, 94, 97]), ': sorted by NumPy algorithm')
(array([ 9, 18, 20, 22, 30, 32, 34, 40, 48, 51, 60, 74, 75, 94, 97]), ': sorted by trained RNN')


(array([[94,  0, 34, 69, 93, 66, 22, 11, 99,  6, 67, 82, 66, 84, 27]]), ': input array')
(array([ 0,  6, 11, 22, 27, 34, 66, 66, 67, 

(array([[64, 58, 67, 54, 11, 97, 83, 93, 50,  5, 39, 71,  6, 94, 88]]), ': input array')
(array([ 5,  6, 11, 39, 50, 54, 58, 64, 67, 71, 83, 88, 93, 94, 97]), ': sorted by NumPy algorithm')
(array([ 5,  6, 11, 39, 50, 54, 58, 64, 67, 71, 83, 88, 93, 94, 97]), ': sorted by trained RNN')


(array([[90, 61, 89, 42, 79, 81, 20, 41, 48, 50, 33, 47, 53, 17, 57]]), ': input array')
(array([17, 20, 33, 41, 42, 47, 48, 50, 53, 57, 61, 79, 81, 89, 90]), ': sorted by NumPy algorithm')
(array([17, 20, 33, 41, 42, 47, 48, 50, 53, 57, 61, 79, 81, 89, 90]), ': sorted by trained RNN')


(array([[82, 87, 84, 24, 70,  8, 51, 79, 79, 98, 59, 73, 74, 61, 97]]), ': input array')
(array([ 8, 24, 51, 59, 61, 70, 73, 74, 79, 79, 82, 84, 87, 97, 98]), ': sorted by NumPy algorithm')
(array([ 8, 24, 51, 59, 61, 70, 73, 74, 79, 79, 82, 84, 87, 97, 98]), ': sorted by trained RNN')


(array([[91, 59, 25, 95, 35, 55, 43, 62, 41, 62, 84,  3, 80, 49, 85]]), ': input array')
(array([ 3, 25, 35, 41, 43, 49, 55, 59, 62, 

(array([[ 8, 19, 64, 56, 89,  8, 80, 21, 49, 97, 32, 20, 20, 42, 73]]), ': input array')
(array([ 8,  8, 19, 20, 20, 21, 32, 42, 49, 56, 64, 73, 80, 89, 97]), ': sorted by NumPy algorithm')
(array([ 8,  8, 19, 20, 20, 21, 32, 42, 49, 56, 64, 73, 80, 89, 97]), ': sorted by trained RNN')


(array([[69, 99, 97, 87, 89,  3, 79, 62, 93, 31, 37, 92, 84, 19, 67]]), ': input array')
(array([ 3, 19, 31, 37, 62, 67, 69, 79, 84, 87, 89, 92, 93, 97, 99]), ': sorted by NumPy algorithm')
(array([ 3, 19, 31, 37, 62, 67, 69, 79, 84, 87, 89, 92, 93, 97, 99]), ': sorted by trained RNN')


(array([[87, 94, 94, 36,  2, 23, 63, 11, 78, 55, 23, 65, 62, 98, 46]]), ': input array')
(array([ 2, 11, 23, 23, 36, 46, 55, 62, 63, 65, 78, 87, 94, 94, 98]), ': sorted by NumPy algorithm')
(array([ 2, 11, 23, 23, 36, 46, 55, 62, 63, 65, 78, 87, 94, 94, 98]), ': sorted by trained RNN')


(array([[34, 88, 73, 54, 47, 45, 52, 65, 81, 24,  1, 43, 61, 28, 77]]), ': input array')
(array([ 1, 24, 28, 34, 43, 45, 47, 52, 54, 

(array([[ 4, 56, 23, 10, 20, 73, 72, 48, 27, 10, 31, 15, 46, 93, 52]]), ': input array')
(array([ 4, 10, 10, 15, 20, 23, 27, 31, 46, 48, 52, 56, 72, 73, 93]), ': sorted by NumPy algorithm')
(array([ 4, 10, 10, 15, 20, 23, 27, 31, 46, 48, 52, 56, 72, 73, 93]), ': sorted by trained RNN')


(array([[85, 27,  2, 24, 87, 39, 38, 14, 79, 70, 61, 60,  0, 32, 54]]), ': input array')
(array([ 0,  2, 14, 24, 27, 32, 38, 39, 54, 60, 61, 70, 79, 85, 87]), ': sorted by NumPy algorithm')
(array([ 0,  2, 14, 24, 27, 32, 38, 39, 54, 60, 61, 70, 79, 85, 87]), ': sorted by trained RNN')


(array([[94, 69, 22, 78, 97, 93, 84, 38, 42, 55, 48, 41, 84, 70, 65]]), ': input array')
(array([22, 38, 41, 42, 48, 55, 65, 69, 70, 78, 84, 84, 93, 94, 97]), ': sorted by NumPy algorithm')
(array([22, 38, 41, 42, 48, 55, 65, 69, 70, 78, 84, 84, 93, 94, 97]), ': sorted by trained RNN')


(array([[40, 94, 51, 21, 46, 54, 46, 62, 96, 89,  5, 34, 87, 55, 11]]), ': input array')
(array([ 5, 11, 21, 34, 40, 46, 46, 51, 54, 

(array([[22, 98, 14, 27,  9, 76,  2, 60,  1, 64, 34,  4, 89, 81, 22]]), ': input array')
(array([ 1,  2,  4,  9, 14, 22, 22, 27, 34, 60, 64, 76, 81, 89, 98]), ': sorted by NumPy algorithm')
(array([ 1,  2,  4,  9, 14, 22, 22, 27, 34, 60, 64, 76, 81, 89, 98]), ': sorted by trained RNN')


(array([[51, 28, 38, 65, 34,  3, 23,  1, 19, 21, 31, 33, 40, 28, 10]]), ': input array')
(array([ 1,  3, 10, 19, 21, 23, 28, 28, 31, 33, 34, 38, 40, 51, 65]), ': sorted by NumPy algorithm')
(array([ 1,  4, 10, 19, 21, 23, 28, 28, 32, 33, 35, 38, 40, 52, 65]), ': sorted by trained RNN')


(array([[88,  6, 88, 95, 84, 61, 43, 85, 44, 42, 76, 68, 91, 34, 65]]), ': input array')
(array([ 6, 34, 42, 43, 44, 61, 65, 68, 76, 84, 85, 88, 88, 91, 95]), ': sorted by NumPy algorithm')
(array([ 6, 34, 42, 43, 44, 61, 65, 68, 76, 84, 85, 88, 88, 91, 95]), ': sorted by trained RNN')


(array([[ 8, 14, 18, 47, 21,  5, 10, 43, 51, 13, 73, 61, 76, 93, 52]]), ': input array')
(array([ 5,  8, 10, 13, 14, 18, 21, 43, 47, 

(array([[58, 34, 67, 94, 81, 32, 24, 99, 93,  7, 24, 72, 91, 52, 21]]), ': input array')
(array([ 7, 21, 24, 24, 32, 34, 52, 58, 67, 72, 81, 91, 93, 94, 99]), ': sorted by NumPy algorithm')
(array([ 7, 21, 24, 24, 32, 34, 52, 58, 67, 72, 81, 91, 93, 94, 99]), ': sorted by trained RNN')


(array([[96, 75, 67, 53, 45, 21,  3, 31, 10, 65, 51, 98,  2, 11, 20]]), ': input array')
(array([ 2,  3, 10, 11, 20, 21, 31, 45, 51, 53, 65, 67, 75, 96, 98]), ': sorted by NumPy algorithm')
(array([ 2,  3, 10, 11, 20, 21, 31, 45, 51, 53, 65, 67, 75, 96, 98]), ': sorted by trained RNN')


(array([[10, 84, 32,  4, 44, 40, 92, 83, 20, 88, 28,  8, 16, 50, 85]]), ': input array')
(array([ 4,  8, 10, 16, 20, 28, 32, 40, 44, 50, 83, 84, 85, 88, 92]), ': sorted by NumPy algorithm')
(array([ 4,  8, 10, 16, 20, 28, 32, 40, 44, 50, 83, 84, 85, 88, 92]), ': sorted by trained RNN')


(array([[20, 21, 49, 40, 39,  2, 73, 14, 54, 61, 57, 96, 20, 50, 96]]), ': input array')
(array([ 2, 14, 20, 20, 21, 39, 40, 49, 50, 

(array([[38, 64, 57, 32, 20, 97, 40, 98, 75, 67, 38,  5, 61, 71, 11]]), ': input array')
(array([ 5, 11, 20, 32, 38, 38, 40, 57, 61, 64, 67, 71, 75, 97, 98]), ': sorted by NumPy algorithm')
(array([ 5, 11, 20, 32, 38, 38, 40, 57, 61, 64, 67, 71, 75, 97, 98]), ': sorted by trained RNN')


(array([[50,  1, 22, 85, 92, 79, 67, 89, 93,  8, 22, 58, 98, 19, 18]]), ': input array')
(array([ 1,  8, 18, 19, 22, 22, 50, 58, 67, 79, 85, 89, 92, 93, 98]), ': sorted by NumPy algorithm')
(array([ 1,  8, 18, 19, 22, 22, 50, 58, 67, 79, 85, 89, 92, 93, 98]), ': sorted by trained RNN')


(array([[57, 75, 38, 49, 75, 90, 69, 89, 67, 52, 65, 50, 14, 65, 80]]), ': input array')
(array([14, 38, 49, 50, 52, 57, 65, 65, 67, 69, 75, 75, 80, 89, 90]), ': sorted by NumPy algorithm')
(array([14, 38, 49, 50, 52, 57, 65, 65, 67, 69, 75, 75, 80, 89, 90]), ': sorted by trained RNN')


(array([[43, 91, 60, 27, 38, 80, 36, 98, 57, 54, 28,  3, 14, 95, 56]]), ': input array')
(array([ 3, 14, 27, 28, 36, 38, 43, 54, 56, 

(array([[15, 83, 96, 77, 13, 41, 16, 30,  1, 33, 53,  7, 56, 33, 30]]), ': input array')
(array([ 1,  7, 13, 15, 16, 30, 30, 33, 33, 41, 53, 56, 77, 83, 96]), ': sorted by NumPy algorithm')
(array([ 1,  7, 13, 15, 16, 30, 30, 33, 33, 41, 53, 56, 77, 83, 96]), ': sorted by trained RNN')


(array([[90, 67,  1, 18, 52, 40, 50, 84, 64, 59, 32, 15, 69, 24,  5]]), ': input array')
(array([ 1,  5, 15, 18, 24, 32, 40, 50, 52, 59, 64, 67, 69, 84, 90]), ': sorted by NumPy algorithm')
(array([ 1,  5, 15, 18, 24, 32, 40, 50, 52, 59, 64, 67, 69, 84, 90]), ': sorted by trained RNN')


(array([[95, 55, 23, 88, 71, 51, 57, 96, 30, 10, 30, 59, 92, 62, 15]]), ': input array')
(array([10, 15, 23, 30, 30, 51, 55, 57, 59, 62, 71, 88, 92, 95, 96]), ': sorted by NumPy algorithm')
(array([10, 15, 23, 30, 30, 51, 55, 57, 59, 62, 71, 88, 92, 95, 96]), ': sorted by trained RNN')


(array([[39, 15, 75, 66, 61, 53,  1, 50, 91,  4, 73, 33, 53, 28,  3]]), ': input array')
(array([ 1,  3,  4, 15, 28, 33, 39, 50, 53, 

(array([[92, 94, 81, 62,  6,  6, 70, 53, 43, 63, 81, 88, 16, 53, 20]]), ': input array')
(array([ 6,  6, 16, 20, 43, 53, 53, 62, 63, 70, 81, 81, 88, 92, 94]), ': sorted by NumPy algorithm')
(array([ 6,  6, 16, 20, 43, 53, 53, 62, 63, 70, 81, 81, 88, 92, 94]), ': sorted by trained RNN')


(array([[63, 27, 71, 65, 68, 82, 66, 60, 57, 28, 24, 91, 50, 13, 19]]), ': input array')
(array([13, 19, 24, 27, 28, 50, 57, 60, 63, 65, 66, 68, 71, 82, 91]), ': sorted by NumPy algorithm')
(array([13, 19, 24, 27, 28, 50, 57, 60, 63, 65, 66, 68, 71, 82, 91]), ': sorted by trained RNN')


(array([[86, 59, 60, 26, 50, 37, 86, 39, 42, 69, 96, 31, 33, 48, 20]]), ': input array')
(array([20, 26, 31, 33, 37, 39, 42, 48, 50, 59, 60, 69, 86, 86, 96]), ': sorted by NumPy algorithm')
(array([20, 26, 31, 33, 37, 39, 42, 48, 50, 59, 60, 69, 86, 86, 96]), ': sorted by trained RNN')


(array([[71, 85, 14,  6, 53, 12, 57, 27, 19, 52, 98, 16, 60, 28, 50]]), ': input array')
(array([ 6, 12, 14, 16, 19, 27, 28, 50, 52, 

(array([[51, 96, 93, 39, 58,  2, 26, 47, 56, 27, 72, 70, 18, 25, 37]]), ': input array')
(array([ 2, 18, 25, 26, 27, 37, 39, 47, 51, 56, 58, 70, 72, 93, 96]), ': sorted by NumPy algorithm')
(array([ 2, 18, 25, 26, 27, 37, 39, 47, 51, 56, 58, 70, 72, 93, 96]), ': sorted by trained RNN')


(array([[69, 18, 69, 23, 49, 78, 14, 55, 77, 78, 51, 76, 86, 29, 78]]), ': input array')
(array([14, 18, 23, 29, 49, 51, 55, 69, 69, 76, 77, 78, 78, 78, 86]), ': sorted by NumPy algorithm')
(array([14, 18, 23, 29, 49, 51, 55, 69, 69, 76, 77, 78, 78, 78, 86]), ': sorted by trained RNN')


(array([[ 4, 79,  5, 61, 64, 29, 92, 18, 68,  0, 14, 78, 78, 89, 57]]), ': input array')
(array([ 0,  4,  5, 14, 18, 29, 57, 61, 64, 68, 78, 78, 79, 89, 92]), ': sorted by NumPy algorithm')
(array([ 0,  4,  5, 14, 18, 29, 57, 61, 64, 68, 78, 78, 79, 89, 92]), ': sorted by trained RNN')


(array([[ 0, 20, 53, 34, 58, 15, 22, 48, 89, 96, 15, 49, 10, 74, 55]]), ': input array')
(array([ 0, 10, 15, 15, 20, 22, 34, 48, 49, 

(array([[ 9,  8,  4, 80, 57, 32, 36, 65, 11, 31, 59, 72, 52, 78, 98]]), ': input array')
(array([ 4,  8,  9, 11, 31, 32, 36, 52, 57, 59, 65, 72, 78, 80, 98]), ': sorted by NumPy algorithm')
(array([ 4,  8,  9, 11, 31, 32, 36, 52, 57, 59, 65, 72, 78, 80, 98]), ': sorted by trained RNN')


(array([[ 1, 30,  2, 56, 81, 30,  1, 25, 18, 44, 97, 43,  6,  3, 42]]), ': input array')
(array([ 1,  1,  2,  3,  6, 18, 25, 30, 30, 42, 43, 44, 56, 81, 97]), ': sorted by NumPy algorithm')
(array([ 1,  1,  2,  3,  6, 18, 25, 30, 30, 42, 43, 44, 56, 81, 97]), ': sorted by trained RNN')


(array([[61, 90, 23, 21,  8, 56, 25, 93, 90, 26, 77, 11, 61,  3, 19]]), ': input array')
(array([ 3,  8, 11, 19, 21, 23, 25, 26, 56, 61, 61, 77, 90, 90, 93]), ': sorted by NumPy algorithm')
(array([ 3,  8, 11, 19, 21, 23, 25, 26, 56, 61, 61, 77, 90, 90, 93]), ': sorted by trained RNN')


(array([[84, 60, 25, 12, 42,  0, 92, 21, 33, 65, 37, 72, 87, 34, 19]]), ': input array')
(array([ 0, 12, 19, 21, 25, 33, 34, 37, 42, 

(array([[68, 71, 15,  2, 86, 57, 65, 19, 86, 16, 15, 80, 48, 74, 21]]), ': input array')
(array([ 2, 15, 15, 16, 19, 21, 48, 57, 65, 68, 71, 74, 80, 86, 86]), ': sorted by NumPy algorithm')
(array([ 2, 15, 15, 16, 19, 21, 48, 57, 65, 68, 71, 74, 80, 86, 86]), ': sorted by trained RNN')


(array([[16, 39, 67, 76, 83, 94, 55,  4, 80, 29, 59, 80, 52, 23, 34]]), ': input array')
(array([ 4, 16, 23, 29, 34, 39, 52, 55, 59, 67, 76, 80, 80, 83, 94]), ': sorted by NumPy algorithm')
(array([ 4, 16, 23, 29, 34, 39, 52, 55, 59, 67, 76, 80, 80, 83, 94]), ': sorted by trained RNN')


(array([[ 9, 42, 79, 47, 91,  8, 11, 49, 50, 75, 59, 76, 48, 26, 88]]), ': input array')
(array([ 8,  9, 11, 26, 42, 47, 48, 49, 50, 59, 75, 76, 79, 88, 91]), ': sorted by NumPy algorithm')
(array([ 8,  9, 11, 26, 42, 47, 48, 49, 50, 59, 75, 76, 79, 88, 91]), ': sorted by trained RNN')


(array([[40, 87, 70, 55, 19, 57, 22, 83, 28, 62,  1, 54, 44,  9, 68]]), ': input array')
(array([ 1,  9, 19, 22, 28, 40, 44, 54, 55, 

(array([[58,  5, 13,  3, 95, 84, 38, 60, 26, 17, 38, 49, 17, 65, 92]]), ': input array')
(array([ 3,  5, 13, 17, 17, 26, 38, 38, 49, 58, 60, 65, 84, 92, 95]), ': sorted by NumPy algorithm')
(array([ 3,  5, 13, 17, 17, 26, 38, 38, 49, 58, 60, 65, 84, 92, 95]), ': sorted by trained RNN')


(array([[59, 11, 87, 98, 76, 29, 22, 35, 92, 14, 93, 79, 47, 37, 51]]), ': input array')
(array([11, 14, 22, 29, 35, 37, 47, 51, 59, 76, 79, 87, 92, 93, 98]), ': sorted by NumPy algorithm')
(array([11, 14, 22, 29, 35, 37, 47, 51, 59, 76, 79, 87, 92, 93, 98]), ': sorted by trained RNN')


(array([[19, 79, 40, 81, 34, 43, 29,  1, 83, 69, 92, 61, 70, 81, 86]]), ': input array')
(array([ 1, 19, 29, 34, 40, 43, 61, 69, 70, 79, 81, 81, 83, 86, 92]), ': sorted by NumPy algorithm')
(array([ 1, 19, 29, 34, 40, 43, 61, 69, 70, 79, 81, 81, 83, 86, 92]), ': sorted by trained RNN')


(array([[37, 28, 59, 41, 32, 50, 18, 77, 13, 53, 88, 56, 81, 52, 32]]), ': input array')
(array([13, 18, 28, 32, 32, 37, 41, 50, 52, 

(array([[71, 78, 29, 90, 32, 45,  1, 65, 77, 15, 60, 26, 85, 67, 45]]), ': input array')
(array([ 1, 15, 26, 29, 32, 45, 45, 60, 65, 67, 71, 77, 78, 85, 90]), ': sorted by NumPy algorithm')
(array([ 1, 15, 26, 29, 32, 45, 45, 60, 65, 67, 71, 77, 78, 85, 90]), ': sorted by trained RNN')


(array([[94,  5, 96,  2, 19, 78, 52, 37, 84,  1, 46, 10, 91, 77, 12]]), ': input array')
(array([ 1,  2,  5, 10, 12, 19, 37, 46, 52, 77, 78, 84, 91, 94, 96]), ': sorted by NumPy algorithm')
(array([ 1,  2,  5, 10, 12, 19, 37, 46, 52, 77, 78, 84, 91, 94, 96]), ': sorted by trained RNN')


(array([[18, 73, 14, 58, 77, 32, 84, 83, 10, 68, 51, 91, 68,  5, 80]]), ': input array')
(array([ 5, 10, 14, 18, 32, 51, 58, 68, 68, 73, 77, 80, 83, 84, 91]), ': sorted by NumPy algorithm')
(array([ 5, 10, 14, 18, 32, 51, 58, 68, 68, 73, 77, 80, 83, 84, 91]), ': sorted by trained RNN')


(array([[28, 28, 17, 85, 58, 53, 82, 76, 14, 63, 29, 81, 38, 42, 94]]), ': input array')
(array([14, 17, 28, 28, 29, 38, 42, 53, 58, 

(array([[54, 32,  9, 88, 69, 70, 75, 97, 82,  8, 66, 57, 54, 32, 66]]), ': input array')
(array([ 8,  9, 32, 32, 54, 54, 57, 66, 66, 69, 70, 75, 82, 88, 97]), ': sorted by NumPy algorithm')
(array([ 8,  9, 32, 32, 54, 54, 57, 66, 66, 69, 70, 75, 82, 88, 97]), ': sorted by trained RNN')


(array([[36, 95,  8, 21, 28, 95, 65, 44,  5,  0, 31, 27, 21, 94,  8]]), ': input array')
(array([ 0,  5,  8,  8, 21, 21, 27, 28, 31, 36, 44, 65, 94, 95, 95]), ': sorted by NumPy algorithm')
(array([ 0,  5,  8,  8, 21, 21, 27, 28, 31, 36, 44, 65, 94, 95, 95]), ': sorted by trained RNN')


(array([[34, 59, 61, 16, 81,  6, 64, 88, 47, 51, 72, 60, 59, 22, 96]]), ': input array')
(array([ 6, 16, 22, 34, 47, 51, 59, 59, 60, 61, 64, 72, 81, 88, 96]), ': sorted by NumPy algorithm')
(array([ 6, 16, 22, 34, 47, 51, 59, 59, 60, 61, 64, 72, 81, 88, 96]), ': sorted by trained RNN')


(array([[96, 13, 41, 31, 77, 69, 73,  1, 21, 99, 10, 92, 38, 82, 57]]), ': input array')
(array([ 1, 10, 13, 21, 31, 38, 41, 57, 69, 

(array([[74, 59,  6, 69, 96, 45, 41, 86, 67, 53, 52, 86,  7, 89, 21]]), ': input array')
(array([ 6,  7, 21, 41, 45, 52, 53, 59, 67, 69, 74, 86, 86, 89, 96]), ': sorted by NumPy algorithm')
(array([ 6,  7, 21, 41, 45, 52, 53, 59, 67, 69, 74, 86, 86, 89, 96]), ': sorted by trained RNN')


(array([[ 8, 48, 67,  8, 48, 21, 81,  1, 13, 74, 14, 40, 71, 40, 30]]), ': input array')
(array([ 1,  8,  8, 13, 14, 21, 30, 40, 40, 48, 48, 67, 71, 74, 81]), ': sorted by NumPy algorithm')
(array([ 1,  8,  8, 13, 14, 21, 30, 40, 40, 48, 48, 67, 71, 74, 81]), ': sorted by trained RNN')


(array([[80,  3, 23, 93, 99, 68, 48, 43,  0, 63, 53, 83, 94, 29,  8]]), ': input array')
(array([ 0,  3,  8, 23, 29, 43, 48, 53, 63, 68, 80, 83, 93, 94, 99]), ': sorted by NumPy algorithm')
(array([ 0,  3,  8, 23, 29, 43, 48, 53, 63, 68, 80, 83, 93, 94, 99]), ': sorted by trained RNN')


(array([[76, 72, 51, 10, 61, 32, 66, 79, 60, 60, 17, 44, 50, 61, 95]]), ': input array')
(array([10, 17, 32, 44, 50, 51, 60, 60, 61, 

In [6]:
test_array = [[16, 60, 59, 14, 18, 77, 70, 94, 17, 22, 69,  4, 27, 12, 82]]
test = encode(test_array, seq_len, max_no)
y = model.predict(test, batch_size = 1)
np_sorted = np.sort(test_array)[0]
rnn_sorted = np.argmax(y, axis=2)[0]
print(rnn_sorted)

[ 4 12 14 16 17 18 22 27 59 60 69 70 77 82 94]


In [7]:
print('\nSuccess Rate: {0:.2f} %'.format(100*win_cnt/numb_trials))


Success Rate: 96.00 %
